---
name: tests

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Test reusable workflow
    uses: ruzickap-org/test-secret/.github/workflows/reusable-workflow.yml@main
    secrets:
      wiz_client_id: ${{ secrets.WIZ_CLIENT_ID }}
      wiz_client_secret: ${{ secrets.WIZ_CLIENT_SECRET }}
